spring:
  main:
    allow-circular-references: true
  security:
    user:
      name: oracleai
      password: oracleai

  web:
    resources:
      static-locations: classpath:/static/

  mvc:
    cors:
      allowed-origin-patterns: ["*"]  # ✅ Allow all origins
      allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed-headers: ["*"]

  servlet:
    websocket:
      buffer-size: 65536  # ✅ Increase WebSocket buffer size
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

  cloud:
    oci:
      config:
        type: INSTANCE_PRINCIPAL

  datasource:
    username: ${DB_USER:financial} # Default to 'financial', overridden by environment variable DB_USER
    password: ${DB_PASSWORD:Welcome12345} # Default to 'Welcome12345', overridden by environment variable DB_PASSWORD
    url: ${DB_URL:jdbc:oracle:thin:@financialdb_high?TNS_ADMIN=/Users/pparkins/Downloads/Wallet_financialdb} # Default URL, overridden by environment variable DB_URL

#  ai:
#    vectorstore:
#      oracle:
#        index-type: IVF
#        distance-type: COSINE
#        dimensions: 1536

#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    org.springframework.web.cors: DEBUG
#    org.springframework.web.socket: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#server:
#  port: 8090
##  port: 8444
##  port: 443
#  tomcat:
#    max-swallow-size: 200MB
#  ssl:
#    enabled: false
#    key-store-type: PKCS12
##    key-store: classpath:keystore.p12
#    key-store: classpath:aiholoorg.p12
#    key-store-password: Welcome1
##    key-alias: springboot
#    key-alias: aiholoorg
server:
  #  port: 443
  #  port: 8444
  port: 8080
  tomcat:
    max-swallow-size: 200MB
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
#    key-store: classpath:oracledatabasefinancialorg.p12
#    key-store-password: Welcome1
#    key-alias: springboot
#    key-alias: oracledatabasefinancialorg