apiVersion: v1
kind: Service
metadata:
  name: grafana-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
