apiVersion: v1
kind: Service
metadata:
  name: graph
  namespace: financial
spec:
  type: ClusterIP
  selector:
    app: graph-circular-payments
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080