apiVersion: v1
kind: Service
metadata:
  name: agentic-rag
  labels:
    app: agentic-rag
spec:
  type: LoadBalancer  # Use NodePort if LoadBalancer is not available
  ports:
  - port: 80
    targetPort: 7860
    protocol: TCP
    name: http
  selector:
    app: agentic-rag 